version: '3.8'

services:
  prod:
    build: .
    container_name: odyssey-prod
    ports:
      - "25565:25565"
    volumes:
      - "/odyssey/data/prod/worlds:/odyssey/worlds"
      - "/odyssey/data/prod/whitelist.json:/odyssey/whitelist.json"

  dev:
    build: .
    container_name: odyssey-dev
    ports:
      - "25566:25565"
    volumes:
      - "/odyssey/data/dev/worlds:/odyssey/worlds"
      - "/odyssey/data/prod/whitelist.json:/odyssey/whitelist.json"
